remote_theme: thuhcsi/slate
title: Joint Multi-scale Cross-lingual Speaking StyleTransfer with Bidirectional Attention Mechanismfor Automatic Dubbing
description: Submitted to TASLP-2022.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
