remote_theme: thuhcsi/slate
title: Joint Multi-scale Cross-lingual Speaking Style Transfer with Bidirectional Attention Mechanism for Automatic Dubbing
description: Submitted to TASLP.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
